# Generated by Django 4.2.2 on 2023-06-20 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='room',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='AkhjlZOpDQyxDXTfDEcQ', max_length=255, unique=True),
        ),
    ]
