# Generated by Django 4.2.2 on 2023-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_recipient_remove_room_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
